### ISSUE TITLE
Estimate user's current region using db ip Svelte + Backend + Postgres

### ISSUE THREAD

**Issue by kylerchin** [catenarytransit/catenary-backend#25]

**Comment by kylerchin** [comment]
@quacksire @samuelbeepdev can you please validate that this works?

Thanks.

**Comment by quacksire** [comment]
This seems like an unnecessary reinvention of the wheel

**Comment by kylerchin** [comment]
I do not wish to rely on cloudflare workers. Catenary backend should be able to be run without vendor lockin, or be using workers on someone's personal account, or workers on the cloud at all.
